apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5ST34/TMAzH/xXk52wc6902KvFwAiEhpBPix14QD27ibaFpEsXJ7tDU/x25XQecdBP3aNf++Otv3CNgtBtKbIOHWgJ6yOQl5Hm75rkNLw+vQEFrvYEa3hbOoftMHErS9I621tssvQo6ymgwI9RHQO9DRvnAEobmJ+nMlOfJhrnGnB0J2QoS1JPfw72nNNsd2qelqRcfrTdvLui6DPfYkdCNGbAV/6n4r16OqAUAvQKdaNj5q+2IM3YRal+cU+CwIXfRiT3yHmpYLa9eL7S5uW5wWW31qtJm1axXi/X1YklLuqHVVVWRIZl2SXmvgCNpmbhLoUSo4fFqg3gpOL3srXBAQXQloTuDQQFbvysO05QTekzElA70zbc+3Pv3lpxhqLfomBSwDlG03U0GGVBwGK+Mof5+nMQPp8V6T91wNiGSv/30YVN9OadiCpFStqPWaamHWVsaSp4y8WzSMiujmNn2pCanQuJExlz4mW29gvxrWGJ8MpDMUG/GCuGGhDs6Nfz4ZxJqTTGTuXvk8t8GDycTvLGn/2S8FaGS2ZzNkmzf/w4AAP//r7lyxagDAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition
    objectset.rio.cattle.io/owner-name: addons.k3s.cattle.io
    objectset.rio.cattle.io/owner-namespace: ""
  creationTimestamp: "2024-03-04T21:15:48Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 76092cd54ba63fc73cd7b8728426e6e5e7033ede
  name: addons.k3s.cattle.io
  resourceVersion: "197"
  uid: b8137dac-1a95-435f-9a11-ef0635eb8242
spec:
  conversion:
    strategy: None
  group: k3s.cattle.io
  names:
    kind: Addon
    listKind: AddonList
    plural: addons
    singular: addon
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: Addon
    listKind: AddonList
    plural: addons
    singular: addon
  conditions:
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
