// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema WorkloadEntry
 */
export class WorkloadEntry extends ApiObject {
  /**
   * Returns the apiVersion and kind for "WorkloadEntry"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'networking.istio.io/v1alpha3',
    kind: 'WorkloadEntry',
  }

  /**
   * Renders a Kubernetes manifest for "WorkloadEntry".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: WorkloadEntryProps = {}): any {
    return {
      ...WorkloadEntry.GVK,
      ...toJson_WorkloadEntryProps(props),
    };
  }

  /**
   * Defines a "WorkloadEntry" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: WorkloadEntryProps = {}) {
    super(scope, id, {
      ...WorkloadEntry.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...WorkloadEntry.GVK,
      ...toJson_WorkloadEntryProps(resolved),
    };
  }
}

/**
 * @schema WorkloadEntry
 */
export interface WorkloadEntryProps {
  /**
   * @schema WorkloadEntry#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Configuration affecting VMs onboarded into the mesh. See more details at: https://istio.io/docs/reference/config/networking/workload-entry.html
   *
   * @schema WorkloadEntry#spec
   */
  readonly spec?: WorkloadEntrySpec;

}

/**
 * Converts an object of type 'WorkloadEntryProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkloadEntryProps(obj: WorkloadEntryProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_WorkloadEntrySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Configuration affecting VMs onboarded into the mesh. See more details at: https://istio.io/docs/reference/config/networking/workload-entry.html
 *
 * @schema WorkloadEntrySpec
 */
export interface WorkloadEntrySpec {
  /**
   * Address associated with the network endpoint without the port.
   *
   * @schema WorkloadEntrySpec#address
   */
  readonly address?: string;

  /**
   * One or more labels associated with the endpoint.
   *
   * @schema WorkloadEntrySpec#labels
   */
  readonly labels?: { [key: string]: string };

  /**
   * The locality associated with the endpoint.
   *
   * @schema WorkloadEntrySpec#locality
   */
  readonly locality?: string;

  /**
   * Network enables Istio to group endpoints resident in the same L3 domain/network.
   *
   * @schema WorkloadEntrySpec#network
   */
  readonly network?: string;

  /**
   * Set of ports associated with the endpoint.
   *
   * @schema WorkloadEntrySpec#ports
   */
  readonly ports?: { [key: string]: number };

  /**
   * The service account associated with the workload if a sidecar is present in the workload.
   *
   * @schema WorkloadEntrySpec#serviceAccount
   */
  readonly serviceAccount?: string;

  /**
   * The load balancing weight associated with the endpoint.
   *
   * @schema WorkloadEntrySpec#weight
   */
  readonly weight?: number;

}

/**
 * Converts an object of type 'WorkloadEntrySpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkloadEntrySpec(obj: WorkloadEntrySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'address': obj.address,
    'labels': ((obj.labels) === undefined) ? undefined : (Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'locality': obj.locality,
    'network': obj.network,
    'ports': ((obj.ports) === undefined) ? undefined : (Object.entries(obj.ports).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'serviceAccount': obj.serviceAccount,
    'weight': obj.weight,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema WorkloadEntryV1Beta1
 */
export class WorkloadEntryV1Beta1 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "WorkloadEntryV1Beta1"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'networking.istio.io/v1beta1',
    kind: 'WorkloadEntry',
  }

  /**
   * Renders a Kubernetes manifest for "WorkloadEntryV1Beta1".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: WorkloadEntryV1Beta1Props = {}): any {
    return {
      ...WorkloadEntryV1Beta1.GVK,
      ...toJson_WorkloadEntryV1Beta1Props(props),
    };
  }

  /**
   * Defines a "WorkloadEntryV1Beta1" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: WorkloadEntryV1Beta1Props = {}) {
    super(scope, id, {
      ...WorkloadEntryV1Beta1.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...WorkloadEntryV1Beta1.GVK,
      ...toJson_WorkloadEntryV1Beta1Props(resolved),
    };
  }
}

/**
 * @schema WorkloadEntryV1Beta1
 */
export interface WorkloadEntryV1Beta1Props {
  /**
   * @schema WorkloadEntryV1Beta1#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * Configuration affecting VMs onboarded into the mesh. See more details at: https://istio.io/docs/reference/config/networking/workload-entry.html
   *
   * @schema WorkloadEntryV1Beta1#spec
   */
  readonly spec?: WorkloadEntryV1Beta1Spec;

}

/**
 * Converts an object of type 'WorkloadEntryV1Beta1Props' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkloadEntryV1Beta1Props(obj: WorkloadEntryV1Beta1Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_WorkloadEntryV1Beta1Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Configuration affecting VMs onboarded into the mesh. See more details at: https://istio.io/docs/reference/config/networking/workload-entry.html
 *
 * @schema WorkloadEntryV1Beta1Spec
 */
export interface WorkloadEntryV1Beta1Spec {
  /**
   * Address associated with the network endpoint without the port.
   *
   * @schema WorkloadEntryV1Beta1Spec#address
   */
  readonly address?: string;

  /**
   * One or more labels associated with the endpoint.
   *
   * @schema WorkloadEntryV1Beta1Spec#labels
   */
  readonly labels?: { [key: string]: string };

  /**
   * The locality associated with the endpoint.
   *
   * @schema WorkloadEntryV1Beta1Spec#locality
   */
  readonly locality?: string;

  /**
   * Network enables Istio to group endpoints resident in the same L3 domain/network.
   *
   * @schema WorkloadEntryV1Beta1Spec#network
   */
  readonly network?: string;

  /**
   * Set of ports associated with the endpoint.
   *
   * @schema WorkloadEntryV1Beta1Spec#ports
   */
  readonly ports?: { [key: string]: number };

  /**
   * The service account associated with the workload if a sidecar is present in the workload.
   *
   * @schema WorkloadEntryV1Beta1Spec#serviceAccount
   */
  readonly serviceAccount?: string;

  /**
   * The load balancing weight associated with the endpoint.
   *
   * @schema WorkloadEntryV1Beta1Spec#weight
   */
  readonly weight?: number;

}

/**
 * Converts an object of type 'WorkloadEntryV1Beta1Spec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkloadEntryV1Beta1Spec(obj: WorkloadEntryV1Beta1Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'address': obj.address,
    'labels': ((obj.labels) === undefined) ? undefined : (Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'locality': obj.locality,
    'network': obj.network,
    'ports': ((obj.ports) === undefined) ? undefined : (Object.entries(obj.ports).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'serviceAccount': obj.serviceAccount,
    'weight': obj.weight,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

