apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5RTTY/TMBD9K2jOblG73W0biQNahEBIK8RHL4jDxJk0Jo5teezuoir/HU2SLlukLXCLxzNv3nt+OQIGs6PIxjso5EAPiZwced5ueG78y8MCFLTGVVDAbebku0/EPkdNb6g2ziSZVdBRwgoTQnEEdM4nlAuWoy9/kE5MaR6Nn2tMyZIgG4EE9ey9v3cUZ/tD+zw19eKDcdWrC7wugzvsCApoyHa6wZh4Lp+/2/4JgANqQYFegY40CP9iOuKEXYDCZWsVWCzJXrSjQW6ggOUWcb2iJZZ0vV2tV5sV1Zubtd5utnizXS7q60W5WF1tZNtf6fcKOJCWtfvoc5iazwQOEqRjeuR3ZLtbQQMFweaI9mwFKGDj9tlifFqXVSESUzzQV9c6f+/eGrIVQ1GjZVLA2gdhe3eyrAIFhzF8DMW340nOkDjWDXVDmnwg9/rj+93V58dSiD5QTGbkfVL4MGtzSdFRIp6duMzySGZWT2xSzCS2JEyZ/3OsV5B+DiLGRwSpDP3V2CG4PuKepoHvZ5tQawqJqrs/HH9q9BAi7yoz/T5jegSVqt2jWVLt+18BAAD//32jWoG/AwAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition
    objectset.rio.cattle.io/owner-name: helmcharts.helm.cattle.io
    objectset.rio.cattle.io/owner-namespace: ""
  creationTimestamp: "2024-03-04T21:15:48Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 29aa74e2abe5947484ef867c989a6921f51b1438
  name: helmcharts.helm.cattle.io
  resourceVersion: "202"
  uid: 2fe07e4a-a1b8-4aad-9967-e4cdf7254baf
spec:
  conversion:
    strategy: None
  group: helm.cattle.io
  names:
    kind: HelmChart
    listKind: HelmChartList
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: HelmChart
    listKind: HelmChartList
    plural: helmcharts
    singular: helmchart
  conditions:
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
