apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5RTTY8TMQz9K8jntPRDrcpIHFARAiGtEB+9IA5u4mnDZJIoTrqLqvnvyDPThQW2Wo7xx7Pf88sZMNodJbbBQyUPusvk5cnTZsNTG56f5qCgsd5ABdvCObQfiUNJml5Tbb3N0qugpYwGM0J1BvQ+ZJQEyzPsv5POTHmabJhqzNmRIFuBBPVoPtx6SpPDqXl8NfXsvfXm5ZW9roN7bAkqOJJr9RFT1sHX9sBTCfwqfhIMR9SCBZ0Cnain/9m2xBnbCJUvzilwuCd3VZQj8hEqWMxWi8VsU8/X6+V6szGzVb2aL/WixuVsUxtazleLuXlhZNoTSXQKOJKW4YcUShxbHtDsiUjFePC35NqtYG57TFAQXUno/jEOFLD1h+Iw/Z2V4TERUzrRF9/4cOvfWHKGoarRMSlgHaKwuLlIaUDBabAmQ/X1fKHZ+5H1kdreayGSf/Xh3W756T4UU4iUsh2YXDjfTZqyp+QpE08uu0zKsMykHrfJqZAIlTEX/s+2TkH+0ZMYjgsS6evNUCG4IeGBxoZvDyah1hQzmZs/bvC76L25gjd2/FyDqwSVzO5eLIl23c8AAAD//y6EtavdAwAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition
    objectset.rio.cattle.io/owner-name: helmchartconfigs.helm.cattle.io
    objectset.rio.cattle.io/owner-namespace: ""
  creationTimestamp: "2024-03-04T21:15:48Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 2052208f1663688d05f513c2fa308fde31521d9d
  name: helmchartconfigs.helm.cattle.io
  resourceVersion: "206"
  uid: c1dbfcef-dcad-49ef-bc5c-3c5b69e65dc4
spec:
  conversion:
    strategy: None
  group: helm.cattle.io
  names:
    kind: HelmChartConfig
    listKind: HelmChartConfigList
    plural: helmchartconfigs
    singular: helmchartconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: HelmChartConfig
    listKind: HelmChartConfigList
    plural: helmchartconfigs
    singular: helmchartconfig
  conditions:
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-04T21:15:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
