apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"kopfpeerings.zalando.org"},"spec":{"group":"zalando.org","names":{"kind":"KopfPeering","plural":"kopfpeerings","singular":"kopfpeering"},"scope":"Namespaced","versions":[{"name":"v1","schema":{"openAPIV3Schema":{"properties":{"status":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"type":"object"}},"served":true,"storage":true}]}}
  creationTimestamp: "2024-03-04T23:20:58Z"
  generation: 1
  name: kopfpeerings.zalando.org
  resourceVersion: "34511"
  uid: 43fce727-510f-44f8-9279-5a2833b5b893
spec:
  conversion:
    strategy: None
  group: zalando.org
  names:
    kind: KopfPeering
    listKind: KopfPeeringList
    plural: kopfpeerings
    singular: kopfpeering
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: KopfPeering
    listKind: KopfPeeringList
    plural: kopfpeerings
    singular: kopfpeering
  conditions:
  - lastTransitionTime: "2024-03-04T23:20:58Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-03-04T23:20:58Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
