// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface VaultProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: VaultValues;
}

export class Vault extends Construct {
  public constructor(scope: Construct, id: string, props: VaultProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const { additionalValues, ...valuesWithoutAdditionalValues } = props.values;
      updatedProps = {
        ...props,
        values: {
          ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
          ...additionalValues,
        },
      };
    }

    const finalProps: HelmProps = {
      chart: 'vault',
      repo: 'https://helm.releases.hashicorp.com',
      version: '0.27.0',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema vault
 */
export interface VaultValues {
  /**
   * @schema vault#csi
   */
  readonly csi?: VaultCsi;

  /**
   * @schema vault#global
   */
  readonly global?: { [key: string]: any };

  /**
   * @schema vault#injector
   */
  readonly injector?: VaultInjector;

  /**
   * @schema vault#server
   */
  readonly server?: VaultServer;

  /**
   * @schema vault#serverTelemetry
   */
  readonly serverTelemetry?: VaultServerTelemetry;

  /**
   * @schema vault#ui
   */
  readonly ui?: VaultUi;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema vault#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsi
 */
export interface VaultCsi {
  /**
   * @schema VaultCsi#agent
   */
  readonly agent?: VaultCsiAgent;

  /**
   * @schema VaultCsi#daemonSet
   */
  readonly daemonSet?: VaultCsiDaemonSet;

  /**
   * @schema VaultCsi#debug
   */
  readonly debug?: boolean;

  /**
   * @schema VaultCsi#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultCsi#extraArgs
   */
  readonly extraArgs?: any[];

  /**
   * @schema VaultCsi#image
   */
  readonly image?: VaultCsiImage;

  /**
   * @schema VaultCsi#livenessProbe
   */
  readonly livenessProbe?: VaultCsiLivenessProbe;

  /**
   * @schema VaultCsi#pod
   */
  readonly pod?: VaultCsiPod;

  /**
   * @schema VaultCsi#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema VaultCsi#readinessProbe
   */
  readonly readinessProbe?: VaultCsiReadinessProbe;

  /**
   * @schema VaultCsi#resources
   */
  readonly resources?: any;

  /**
   * @schema VaultCsi#serviceAccount
   */
  readonly serviceAccount?: VaultCsiServiceAccount;

  /**
   * @schema VaultCsi#volumeMounts
   */
  readonly volumeMounts?: any[];

  /**
   * @schema VaultCsi#volumes
   */
  readonly volumes?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsi#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjector
 */
export interface VaultInjector {
  /**
   * @schema VaultInjector#affinity
   */
  readonly affinity?: any;

  /**
   * @schema VaultInjector#agentDefaults
   */
  readonly agentDefaults?: VaultInjectorAgentDefaults;

  /**
   * @schema VaultInjector#agentImage
   */
  readonly agentImage?: VaultInjectorAgentImage;

  /**
   * @schema VaultInjector#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultInjector#authPath
   */
  readonly authPath?: string;

  /**
   * @schema VaultInjector#certs
   */
  readonly certs?: VaultInjectorCerts;

  /**
   * @schema VaultInjector#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultInjector#externalVaultAddr
   */
  readonly externalVaultAddr?: string;

  /**
   * @schema VaultInjector#extraEnvironmentVars
   */
  readonly extraEnvironmentVars?: any;

  /**
   * @schema VaultInjector#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * @schema VaultInjector#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * @schema VaultInjector#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema VaultInjector#image
   */
  readonly image?: VaultInjectorImage;

  /**
   * @schema VaultInjector#leaderElector
   */
  readonly leaderElector?: VaultInjectorLeaderElector;

  /**
   * @schema VaultInjector#logFormat
   */
  readonly logFormat?: string;

  /**
   * @schema VaultInjector#logLevel
   */
  readonly logLevel?: string;

  /**
   * @schema VaultInjector#metrics
   */
  readonly metrics?: VaultInjectorMetrics;

  /**
   * @schema VaultInjector#namespaceSelector
   */
  readonly namespaceSelector?: any;

  /**
   * @schema VaultInjector#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema VaultInjector#objectSelector
   */
  readonly objectSelector?: any;

  /**
   * @schema VaultInjector#podDisruptionBudget
   */
  readonly podDisruptionBudget?: any;

  /**
   * @schema VaultInjector#port
   */
  readonly port?: number;

  /**
   * @schema VaultInjector#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema VaultInjector#replicas
   */
  readonly replicas?: number;

  /**
   * @schema VaultInjector#resources
   */
  readonly resources?: any;

  /**
   * @schema VaultInjector#revokeOnShutdown
   */
  readonly revokeOnShutdown?: boolean;

  /**
   * @schema VaultInjector#securityContext
   */
  readonly securityContext?: VaultInjectorSecurityContext;

  /**
   * @schema VaultInjector#service
   */
  readonly service?: VaultInjectorService;

  /**
   * @schema VaultInjector#serviceAccount
   */
  readonly serviceAccount?: VaultInjectorServiceAccount;

  /**
   * @schema VaultInjector#strategy
   */
  readonly strategy?: any;

  /**
   * @schema VaultInjector#tolerations
   */
  readonly tolerations?: any;

  /**
   * @schema VaultInjector#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any;

  /**
   * @schema VaultInjector#webhook
   */
  readonly webhook?: VaultInjectorWebhook;

  /**
   * @schema VaultInjector#webhookAnnotations
   */
  readonly webhookAnnotations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServer
 */
export interface VaultServer {
  /**
   * @schema VaultServer#affinity
   */
  readonly affinity?: any;

  /**
   * @schema VaultServer#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServer#auditStorage
   */
  readonly auditStorage?: VaultServerAuditStorage;

  /**
   * @schema VaultServer#authDelegator
   */
  readonly authDelegator?: VaultServerAuthDelegator;

  /**
   * @schema VaultServer#dataStorage
   */
  readonly dataStorage?: VaultServerDataStorage;

  /**
   * @schema VaultServer#persistentVolumeClaimRetentionPolicy
   */
  readonly persistentVolumeClaimRetentionPolicy?: VaultServerPersistentVolumeClaimRetentionPolicy;

  /**
   * @schema VaultServer#dev
   */
  readonly dev?: VaultServerDev;

  /**
   * @schema VaultServer#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultServer#enterpriseLicense
   */
  readonly enterpriseLicense?: VaultServerEnterpriseLicense;

  /**
   * @schema VaultServer#extraArgs
   */
  readonly extraArgs?: string;

  /**
   * @schema VaultServer#extraPorts
   */
  readonly extraPorts?: any[];

  /**
   * @schema VaultServer#extraContainers
   */
  readonly extraContainers?: any[];

  /**
   * @schema VaultServer#extraEnvironmentVars
   */
  readonly extraEnvironmentVars?: any;

  /**
   * @schema VaultServer#extraInitContainers
   */
  readonly extraInitContainers?: any[];

  /**
   * @schema VaultServer#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * @schema VaultServer#extraSecretEnvironmentVars
   */
  readonly extraSecretEnvironmentVars?: any[];

  /**
   * @schema VaultServer#extraVolumes
   */
  readonly extraVolumes?: any[];

  /**
   * @schema VaultServer#ha
   */
  readonly ha?: VaultServerHa;

  /**
   * @schema VaultServer#hostAliases
   */
  readonly hostAliases?: any[];

  /**
   * @schema VaultServer#image
   */
  readonly image?: VaultServerImage;

  /**
   * @schema VaultServer#ingress
   */
  readonly ingress?: VaultServerIngress;

  /**
   * @schema VaultServer#livenessProbe
   */
  readonly livenessProbe?: VaultServerLivenessProbe;

  /**
   * @schema VaultServer#logFormat
   */
  readonly logFormat?: string;

  /**
   * @schema VaultServer#logLevel
   */
  readonly logLevel?: string;

  /**
   * @schema VaultServer#networkPolicy
   */
  readonly networkPolicy?: VaultServerNetworkPolicy;

  /**
   * @schema VaultServer#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema VaultServer#postStart
   */
  readonly postStart?: any[];

  /**
   * @schema VaultServer#preStopSleepSeconds
   */
  readonly preStopSleepSeconds?: number;

  /**
   * @schema VaultServer#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema VaultServer#readinessProbe
   */
  readonly readinessProbe?: VaultServerReadinessProbe;

  /**
   * @schema VaultServer#resources
   */
  readonly resources?: any;

  /**
   * @schema VaultServer#route
   */
  readonly route?: VaultServerRoute;

  /**
   * @schema VaultServer#service
   */
  readonly service?: VaultServerService;

  /**
   * @schema VaultServer#serviceAccount
   */
  readonly serviceAccount?: VaultServerServiceAccount;

  /**
   * @schema VaultServer#shareProcessNamespace
   */
  readonly shareProcessNamespace?: boolean;

  /**
   * @schema VaultServer#standalone
   */
  readonly standalone?: VaultServerStandalone;

  /**
   * @schema VaultServer#statefulSet
   */
  readonly statefulSet?: VaultServerStatefulSet;

  /**
   * @schema VaultServer#terminationGracePeriodSeconds
   */
  readonly terminationGracePeriodSeconds?: number;

  /**
   * @schema VaultServer#tolerations
   */
  readonly tolerations?: any;

  /**
   * @schema VaultServer#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any;

  /**
   * @schema VaultServer#updateStrategyType
   */
  readonly updateStrategyType?: string;

  /**
   * @schema VaultServer#volumeMounts
   */
  readonly volumeMounts?: any[];

  /**
   * @schema VaultServer#volumes
   */
  readonly volumes?: any[];

  /**
   * @schema VaultServer#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServer#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerTelemetry
 */
export interface VaultServerTelemetry {
  /**
   * @schema VaultServerTelemetry#prometheusRules
   */
  readonly prometheusRules?: VaultServerTelemetryPrometheusRules;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerTelemetry#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultUi
 */
export interface VaultUi {
  /**
   * @schema VaultUi#activeVaultPodOnly
   */
  readonly activeVaultPodOnly?: boolean;

  /**
   * @schema VaultUi#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultUi#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultUi#externalPort
   */
  readonly externalPort?: number;

  /**
   * @schema VaultUi#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: string;

  /**
   * @schema VaultUi#publishNotReadyAddresses
   */
  readonly publishNotReadyAddresses?: boolean;

  /**
   * @schema VaultUi#serviceNodePort
   */
  readonly serviceNodePort?: number;

  /**
   * @schema VaultUi#serviceType
   */
  readonly serviceType?: string;

  /**
   * @schema VaultUi#targetPort
   */
  readonly targetPort?: number;

  /**
   * @schema VaultUi#serviceIPFamilyPolicy
   */
  readonly serviceIpFamilyPolicy?: string;

  /**
   * @schema VaultUi#serviceIPFamilies
   */
  readonly serviceIpFamilies?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultUi#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiAgent
 */
export interface VaultCsiAgent {
  /**
   * @schema VaultCsiAgent#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultCsiAgent#extraArgs
   */
  readonly extraArgs?: any[];

  /**
   * @schema VaultCsiAgent#image
   */
  readonly image?: VaultCsiAgentImage;

  /**
   * @schema VaultCsiAgent#logFormat
   */
  readonly logFormat?: string;

  /**
   * @schema VaultCsiAgent#logLevel
   */
  readonly logLevel?: string;

  /**
   * @schema VaultCsiAgent#resources
   */
  readonly resources?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiAgent#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiDaemonSet
 */
export interface VaultCsiDaemonSet {
  /**
   * @schema VaultCsiDaemonSet#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultCsiDaemonSet#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * @schema VaultCsiDaemonSet#kubeletRootDir
   */
  readonly kubeletRootDir?: string;

  /**
   * @schema VaultCsiDaemonSet#providersDir
   */
  readonly providersDir?: string;

  /**
   * @schema VaultCsiDaemonSet#securityContext
   */
  readonly securityContext?: VaultCsiDaemonSetSecurityContext;

  /**
   * @schema VaultCsiDaemonSet#updateStrategy
   */
  readonly updateStrategy?: VaultCsiDaemonSetUpdateStrategy;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiDaemonSet#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiImage
 */
export interface VaultCsiImage {
  /**
   * @schema VaultCsiImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema VaultCsiImage#repository
   */
  readonly repository?: string;

  /**
   * @schema VaultCsiImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiLivenessProbe
 */
export interface VaultCsiLivenessProbe {
  /**
   * @schema VaultCsiLivenessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema VaultCsiLivenessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * @schema VaultCsiLivenessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * @schema VaultCsiLivenessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * @schema VaultCsiLivenessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiLivenessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiPod
 */
export interface VaultCsiPod {
  /**
   * @schema VaultCsiPod#affinity
   */
  readonly affinity?: any;

  /**
   * @schema VaultCsiPod#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultCsiPod#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * @schema VaultCsiPod#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema VaultCsiPod#tolerations
   */
  readonly tolerations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiPod#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiReadinessProbe
 */
export interface VaultCsiReadinessProbe {
  /**
   * @schema VaultCsiReadinessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema VaultCsiReadinessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * @schema VaultCsiReadinessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * @schema VaultCsiReadinessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * @schema VaultCsiReadinessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiServiceAccount
 */
export interface VaultCsiServiceAccount {
  /**
   * @schema VaultCsiServiceAccount#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultCsiServiceAccount#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorAgentDefaults
 */
export interface VaultInjectorAgentDefaults {
  /**
   * @schema VaultInjectorAgentDefaults#cpuLimit
   */
  readonly cpuLimit?: string;

  /**
   * @schema VaultInjectorAgentDefaults#cpuRequest
   */
  readonly cpuRequest?: string;

  /**
   * @schema VaultInjectorAgentDefaults#memLimit
   */
  readonly memLimit?: string;

  /**
   * @schema VaultInjectorAgentDefaults#memRequest
   */
  readonly memRequest?: string;

  /**
   * @schema VaultInjectorAgentDefaults#ephemeralLimit
   */
  readonly ephemeralLimit?: string;

  /**
   * @schema VaultInjectorAgentDefaults#ephemeralRequest
   */
  readonly ephemeralRequest?: string;

  /**
   * @schema VaultInjectorAgentDefaults#template
   */
  readonly template?: string;

  /**
   * @schema VaultInjectorAgentDefaults#templateConfig
   */
  readonly templateConfig?: VaultInjectorAgentDefaultsTemplateConfig;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorAgentDefaults#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorAgentImage
 */
export interface VaultInjectorAgentImage {
  /**
   * @schema VaultInjectorAgentImage#repository
   */
  readonly repository?: string;

  /**
   * @schema VaultInjectorAgentImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorAgentImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorCerts
 */
export interface VaultInjectorCerts {
  /**
   * @schema VaultInjectorCerts#caBundle
   */
  readonly caBundle?: string;

  /**
   * @schema VaultInjectorCerts#certName
   */
  readonly certName?: string;

  /**
   * @schema VaultInjectorCerts#keyName
   */
  readonly keyName?: string;

  /**
   * @schema VaultInjectorCerts#secretName
   */
  readonly secretName?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorCerts#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorImage
 */
export interface VaultInjectorImage {
  /**
   * @schema VaultInjectorImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema VaultInjectorImage#repository
   */
  readonly repository?: string;

  /**
   * @schema VaultInjectorImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorLeaderElector
 */
export interface VaultInjectorLeaderElector {
  /**
   * @schema VaultInjectorLeaderElector#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorLeaderElector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorMetrics
 */
export interface VaultInjectorMetrics {
  /**
   * @schema VaultInjectorMetrics#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorSecurityContext
 */
export interface VaultInjectorSecurityContext {
  /**
   * @schema VaultInjectorSecurityContext#container
   */
  readonly container?: any;

  /**
   * @schema VaultInjectorSecurityContext#pod
   */
  readonly pod?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorService
 */
export interface VaultInjectorService {
  /**
   * @schema VaultInjectorService#annotations
   */
  readonly annotations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorServiceAccount
 */
export interface VaultInjectorServiceAccount {
  /**
   * @schema VaultInjectorServiceAccount#annotations
   */
  readonly annotations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorWebhook
 */
export interface VaultInjectorWebhook {
  /**
   * @schema VaultInjectorWebhook#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultInjectorWebhook#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * @schema VaultInjectorWebhook#matchPolicy
   */
  readonly matchPolicy?: string;

  /**
   * @schema VaultInjectorWebhook#namespaceSelector
   */
  readonly namespaceSelector?: any;

  /**
   * @schema VaultInjectorWebhook#objectSelector
   */
  readonly objectSelector?: any;

  /**
   * @schema VaultInjectorWebhook#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorWebhook#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerAuditStorage
 */
export interface VaultServerAuditStorage {
  /**
   * @schema VaultServerAuditStorage#accessMode
   */
  readonly accessMode?: string;

  /**
   * @schema VaultServerAuditStorage#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerAuditStorage#labels
   */
  readonly labels?: any;

  /**
   * @schema VaultServerAuditStorage#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultServerAuditStorage#mountPath
   */
  readonly mountPath?: string;

  /**
   * @schema VaultServerAuditStorage#size
   */
  readonly size?: string;

  /**
   * @schema VaultServerAuditStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerAuditStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerAuthDelegator
 */
export interface VaultServerAuthDelegator {
  /**
   * @schema VaultServerAuthDelegator#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerAuthDelegator#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerDataStorage
 */
export interface VaultServerDataStorage {
  /**
   * @schema VaultServerDataStorage#accessMode
   */
  readonly accessMode?: string;

  /**
   * @schema VaultServerDataStorage#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerDataStorage#labels
   */
  readonly labels?: any;

  /**
   * @schema VaultServerDataStorage#enabled
   */
  readonly enabled?: any;

  /**
   * @schema VaultServerDataStorage#mountPath
   */
  readonly mountPath?: string;

  /**
   * @schema VaultServerDataStorage#size
   */
  readonly size?: string;

  /**
   * @schema VaultServerDataStorage#storageClass
   */
  readonly storageClass?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerDataStorage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerPersistentVolumeClaimRetentionPolicy
 */
export interface VaultServerPersistentVolumeClaimRetentionPolicy {
  /**
   * @schema VaultServerPersistentVolumeClaimRetentionPolicy#whenDeleted
   */
  readonly whenDeleted?: string;

  /**
   * @schema VaultServerPersistentVolumeClaimRetentionPolicy#whenScaled
   */
  readonly whenScaled?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerPersistentVolumeClaimRetentionPolicy#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerDev
 */
export interface VaultServerDev {
  /**
   * @schema VaultServerDev#devRootToken
   */
  readonly devRootToken?: string;

  /**
   * @schema VaultServerDev#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerDev#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerEnterpriseLicense
 */
export interface VaultServerEnterpriseLicense {
  /**
   * @schema VaultServerEnterpriseLicense#secretKey
   */
  readonly secretKey?: string;

  /**
   * @schema VaultServerEnterpriseLicense#secretName
   */
  readonly secretName?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerEnterpriseLicense#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerHa
 */
export interface VaultServerHa {
  /**
   * @schema VaultServerHa#apiAddr
   */
  readonly apiAddr?: string;

  /**
   * @schema VaultServerHa#clusterAddr
   */
  readonly clusterAddr?: string;

  /**
   * @schema VaultServerHa#config
   */
  readonly config?: any;

  /**
   * @schema VaultServerHa#disruptionBudget
   */
  readonly disruptionBudget?: VaultServerHaDisruptionBudget;

  /**
   * @schema VaultServerHa#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerHa#raft
   */
  readonly raft?: VaultServerHaRaft;

  /**
   * @schema VaultServerHa#replicas
   */
  readonly replicas?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerHa#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerImage
 */
export interface VaultServerImage {
  /**
   * @schema VaultServerImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema VaultServerImage#repository
   */
  readonly repository?: string;

  /**
   * @schema VaultServerImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerIngress
 */
export interface VaultServerIngress {
  /**
   * @schema VaultServerIngress#activeService
   */
  readonly activeService?: boolean;

  /**
   * @schema VaultServerIngress#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerIngress#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerIngress#extraPaths
   */
  readonly extraPaths?: any[];

  /**
   * @schema VaultServerIngress#hosts
   */
  readonly hosts?: VaultServerIngressHosts[];

  /**
   * @schema VaultServerIngress#ingressClassName
   */
  readonly ingressClassName?: string;

  /**
   * @schema VaultServerIngress#labels
   */
  readonly labels?: any;

  /**
   * @schema VaultServerIngress#pathType
   */
  readonly pathType?: string;

  /**
   * @schema VaultServerIngress#tls
   */
  readonly tls?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerIngress#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerLivenessProbe
 */
export interface VaultServerLivenessProbe {
  /**
   * @schema VaultServerLivenessProbe#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerLivenessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema VaultServerLivenessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * @schema VaultServerLivenessProbe#path
   */
  readonly path?: string;

  /**
   * @schema VaultServerLivenessProbe#port
   */
  readonly port?: number;

  /**
   * @schema VaultServerLivenessProbe#execCommand
   */
  readonly execCommand?: any[];

  /**
   * @schema VaultServerLivenessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * @schema VaultServerLivenessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * @schema VaultServerLivenessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerLivenessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerNetworkPolicy
 */
export interface VaultServerNetworkPolicy {
  /**
   * @schema VaultServerNetworkPolicy#egress
   */
  readonly egress?: any[];

  /**
   * @schema VaultServerNetworkPolicy#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerNetworkPolicy#ingress
   */
  readonly ingress?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerNetworkPolicy#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerReadinessProbe
 */
export interface VaultServerReadinessProbe {
  /**
   * @schema VaultServerReadinessProbe#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerReadinessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * @schema VaultServerReadinessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * @schema VaultServerReadinessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * @schema VaultServerReadinessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * @schema VaultServerReadinessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerRoute
 */
export interface VaultServerRoute {
  /**
   * @schema VaultServerRoute#activeService
   */
  readonly activeService?: boolean;

  /**
   * @schema VaultServerRoute#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerRoute#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerRoute#host
   */
  readonly host?: string;

  /**
   * @schema VaultServerRoute#labels
   */
  readonly labels?: any;

  /**
   * @schema VaultServerRoute#tls
   */
  readonly tls?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerRoute#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerService
 */
export interface VaultServerService {
  /**
   * @schema VaultServerService#active
   */
  readonly active?: VaultServerServiceActive;

  /**
   * @schema VaultServerService#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerService#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerService#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: string;

  /**
   * @schema VaultServerService#instanceSelector
   */
  readonly instanceSelector?: VaultServerServiceInstanceSelector;

  /**
   * @schema VaultServerService#port
   */
  readonly port?: number;

  /**
   * @schema VaultServerService#publishNotReadyAddresses
   */
  readonly publishNotReadyAddresses?: boolean;

  /**
   * @schema VaultServerService#standby
   */
  readonly standby?: VaultServerServiceStandby;

  /**
   * @schema VaultServerService#targetPort
   */
  readonly targetPort?: number;

  /**
   * @schema VaultServerService#nodePort
   */
  readonly nodePort?: number;

  /**
   * @schema VaultServerService#activeNodePort
   */
  readonly activeNodePort?: number;

  /**
   * @schema VaultServerService#standbyNodePort
   */
  readonly standbyNodePort?: number;

  /**
   * @schema VaultServerService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: string;

  /**
   * @schema VaultServerService#ipFamilies
   */
  readonly ipFamilies?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerServiceAccount
 */
export interface VaultServerServiceAccount {
  /**
   * @schema VaultServerServiceAccount#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema VaultServerServiceAccount#extraLabels
   */
  readonly extraLabels?: any;

  /**
   * @schema VaultServerServiceAccount#createSecret
   */
  readonly createSecret?: boolean;

  /**
   * @schema VaultServerServiceAccount#name
   */
  readonly name?: string;

  /**
   * @schema VaultServerServiceAccount#serviceDiscovery
   */
  readonly serviceDiscovery?: VaultServerServiceAccountServiceDiscovery;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerStandalone
 */
export interface VaultServerStandalone {
  /**
   * @schema VaultServerStandalone#config
   */
  readonly config?: any;

  /**
   * @schema VaultServerStandalone#enabled
   */
  readonly enabled?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerStandalone#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerStatefulSet
 */
export interface VaultServerStatefulSet {
  /**
   * @schema VaultServerStatefulSet#annotations
   */
  readonly annotations?: any;

  /**
   * @schema VaultServerStatefulSet#securityContext
   */
  readonly securityContext?: VaultServerStatefulSetSecurityContext;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerStatefulSet#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerTelemetryPrometheusRules
 */
export interface VaultServerTelemetryPrometheusRules {
  /**
   * @schema VaultServerTelemetryPrometheusRules#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerTelemetryPrometheusRules#rules
   */
  readonly rules?: any[];

  /**
   * @schema VaultServerTelemetryPrometheusRules#selectors
   */
  readonly selectors?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerTelemetryPrometheusRules#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiAgentImage
 */
export interface VaultCsiAgentImage {
  /**
   * @schema VaultCsiAgentImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema VaultCsiAgentImage#repository
   */
  readonly repository?: string;

  /**
   * @schema VaultCsiAgentImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiAgentImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiDaemonSetSecurityContext
 */
export interface VaultCsiDaemonSetSecurityContext {
  /**
   * @schema VaultCsiDaemonSetSecurityContext#container
   */
  readonly container?: any;

  /**
   * @schema VaultCsiDaemonSetSecurityContext#pod
   */
  readonly pod?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiDaemonSetSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultCsiDaemonSetUpdateStrategy
 */
export interface VaultCsiDaemonSetUpdateStrategy {
  /**
   * @schema VaultCsiDaemonSetUpdateStrategy#maxUnavailable
   */
  readonly maxUnavailable?: string;

  /**
   * @schema VaultCsiDaemonSetUpdateStrategy#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultCsiDaemonSetUpdateStrategy#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultInjectorAgentDefaultsTemplateConfig
 */
export interface VaultInjectorAgentDefaultsTemplateConfig {
  /**
   * @schema VaultInjectorAgentDefaultsTemplateConfig#exitOnRetryFailure
   */
  readonly exitOnRetryFailure?: boolean;

  /**
   * @schema VaultInjectorAgentDefaultsTemplateConfig#staticSecretRenderInterval
   */
  readonly staticSecretRenderInterval?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultInjectorAgentDefaultsTemplateConfig#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerHaDisruptionBudget
 */
export interface VaultServerHaDisruptionBudget {
  /**
   * @schema VaultServerHaDisruptionBudget#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerHaDisruptionBudget#maxUnavailable
   */
  readonly maxUnavailable?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerHaDisruptionBudget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerHaRaft
 */
export interface VaultServerHaRaft {
  /**
   * @schema VaultServerHaRaft#config
   */
  readonly config?: any;

  /**
   * @schema VaultServerHaRaft#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerHaRaft#setNodeId
   */
  readonly setNodeId?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerHaRaft#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerIngressHosts
 */
export interface VaultServerIngressHosts {
  /**
   * @schema VaultServerIngressHosts#host
   */
  readonly host?: string;

  /**
   * @schema VaultServerIngressHosts#paths
   */
  readonly paths?: any[];

}

/**
 * @schema VaultServerServiceActive
 */
export interface VaultServerServiceActive {
  /**
   * @schema VaultServerServiceActive#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerServiceActive#annotations
   */
  readonly annotations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerServiceActive#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerServiceInstanceSelector
 */
export interface VaultServerServiceInstanceSelector {
  /**
   * @schema VaultServerServiceInstanceSelector#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerServiceInstanceSelector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerServiceStandby
 */
export interface VaultServerServiceStandby {
  /**
   * @schema VaultServerServiceStandby#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema VaultServerServiceStandby#annotations
   */
  readonly annotations?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerServiceStandby#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerServiceAccountServiceDiscovery
 */
export interface VaultServerServiceAccountServiceDiscovery {
  /**
   * @schema VaultServerServiceAccountServiceDiscovery#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerServiceAccountServiceDiscovery#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema VaultServerStatefulSetSecurityContext
 */
export interface VaultServerStatefulSetSecurityContext {
  /**
   * @schema VaultServerStatefulSetSecurityContext#container
   */
  readonly container?: any;

  /**
   * @schema VaultServerStatefulSetSecurityContext#pod
   */
  readonly pod?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema VaultServerStatefulSetSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

