// generated by cdk8s
import { Helm, HelmProps } from "cdk8s";
import { Construct } from "constructs";

export interface GatewayProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: GatewayValues;
}

export class Gateway extends Construct {
  public constructor(scope: Construct, id: string, props: GatewayProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const { additionalValues, ...valuesWithoutAdditionalValues } =
        props.values;
      updatedProps = {
        ...props,
        values: {
          ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
          ...additionalValues,
        },
      };
    }

    const finalProps: HelmProps = {
      chart: "gateway",
      repo: "https://istio-release.storage.googleapis.com/charts",
      version: "1.20.3",
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, "Helm", finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): {
    [key: string]: any;
  } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === "object" && prop !== "additionalValues") {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      } else if (
        typeof props[prop] === "object" &&
        prop !== "additionalValues"
      ) {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema gateway
 */
export interface GatewayValues {
  /**
   * @schema gateway#global
   */
  readonly global?: { [key: string]: any };

  /**
   * @schema gateway#affinity
   */
  readonly affinity?: any;

  /**
   * @schema gateway#securityContext
   */
  readonly securityContext?: any;

  /**
   * @schema gateway#containerSecurityContext
   */
  readonly containerSecurityContext?: any;

  /**
   * @schema gateway#kind
   */
  readonly kind?: GatewayKind;

  /**
   * @schema gateway#annotations
   */
  readonly annotations?: { [key: string]: any };

  /**
   * @schema gateway#autoscaling
   */
  readonly autoscaling?: GatewayAutoscaling;

  /**
   * @schema gateway#env
   */
  readonly env?: any;

  /**
   * @schema gateway#labels
   */
  readonly labels?: any;

  /**
   * @schema gateway#name
   */
  readonly name?: string;

  /**
   * @schema gateway#nodeSelector
   */
  readonly nodeSelector?: any;

  /**
   * @schema gateway#podAnnotations
   */
  readonly podAnnotations?: GatewayPodAnnotations;

  /**
   * @schema gateway#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema gateway#resources
   */
  readonly resources?: GatewayResources;

  /**
   * @schema gateway#revision
   */
  readonly revision?: string;

  /**
   * @schema gateway#runAsRoot
   */
  readonly runAsRoot?: boolean;

  /**
   * @schema gateway#unprivilegedPort
   */
  readonly unprivilegedPort?: any;

  /**
   * @schema gateway#service
   */
  readonly service?: GatewayService;

  /**
   * @schema gateway#serviceAccount
   */
  readonly serviceAccount?: GatewayServiceAccount;

  /**
   * @schema gateway#rbac
   */
  readonly rbac?: GatewayRbac;

  /**
   * @schema gateway#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema gateway#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * @schema gateway#networkGateway
   */
  readonly networkGateway?: string;

  /**
   * @schema gateway#imagePullPolicy
   */
  readonly imagePullPolicy?: GatewayImagePullPolicy;

  /**
   * @schema gateway#imagePullSecrets
   */
  readonly imagePullSecrets?: GatewayImagePullSecrets[];

  /**
   * @schema gateway#podDisruptionBudget
   */
  readonly podDisruptionBudget?: GatewayPodDisruptionBudget;

  /**
   * @schema gateway#terminationGracePeriodSeconds
   */
  readonly terminationGracePeriodSeconds?: number;

  /**
   * @schema gateway#volumes
   */
  readonly volumes?: any[];

  /**
   * @schema gateway#volumeMounts
   */
  readonly volumeMounts?: any[];

  /**
   * @schema gateway#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema gateway#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayKind
 */
export enum GatewayKind {
  /** Deployment */
  DEPLOYMENT = "Deployment",
  /** DaemonSet */
  DAEMON_SET = "DaemonSet",
}

/**
 * @schema GatewayAutoscaling
 */
export interface GatewayAutoscaling {
  /**
   * @schema GatewayAutoscaling#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema GatewayAutoscaling#maxReplicas
   */
  readonly maxReplicas?: number;

  /**
   * @schema GatewayAutoscaling#minReplicas
   */
  readonly minReplicas?: number;

  /**
   * @schema GatewayAutoscaling#targetCPUUtilizationPercentage
   */
  readonly targetCpuUtilizationPercentage?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayAutoscaling#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayPodAnnotations
 */
export interface GatewayPodAnnotations {
  /**
   * @schema GatewayPodAnnotations#inject.istio.io/templates
   */
  readonly "injectIstioIo/templates?": string;

  /**
   * @schema GatewayPodAnnotations#prometheus.io/path
   */
  readonly "prometheusIo/path?": string;

  /**
   * @schema GatewayPodAnnotations#prometheus.io/port
   */
  readonly "prometheusIo/port?": string;

  /**
   * @schema GatewayPodAnnotations#prometheus.io/scrape
   */
  readonly "prometheusIo/scrape?": string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayPodAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayResources
 */
export interface GatewayResources {
  /**
   * @schema GatewayResources#limits
   */
  readonly limits?: GatewayResourcesLimits;

  /**
   * @schema GatewayResources#requests
   */
  readonly requests?: GatewayResourcesRequests;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayResources#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayService
 */
export interface GatewayService {
  /**
   * @schema GatewayService#annotations
   */
  readonly annotations?: any;

  /**
   * @schema GatewayService#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: string;

  /**
   * @schema GatewayService#loadBalancerIP
   */
  readonly loadBalancerIp?: string;

  /**
   * @schema GatewayService#loadBalancerSourceRanges
   */
  readonly loadBalancerSourceRanges?: any[];

  /**
   * @schema GatewayService#ipFamilies
   */
  readonly ipFamilies?: any;

  /**
   * @schema GatewayService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: GatewayServiceIpFamilyPolicy;

  /**
   * @schema GatewayService#ports
   */
  readonly ports?: GatewayServicePorts[];

  /**
   * @schema GatewayService#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayServiceAccount
 */
export interface GatewayServiceAccount {
  /**
   * @schema GatewayServiceAccount#annotations
   */
  readonly annotations?: any;

  /**
   * @schema GatewayServiceAccount#name
   */
  readonly name?: string;

  /**
   * @schema GatewayServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayRbac
 */
export interface GatewayRbac {
  /**
   * @schema GatewayRbac#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayImagePullPolicy
 */
export enum GatewayImagePullPolicy {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
  /** Never */
  NEVER = "Never",
}

/**
 * @schema GatewayImagePullSecrets
 */
export interface GatewayImagePullSecrets {
  /**
   * @schema GatewayImagePullSecrets#name
   */
  readonly name?: string;
}

/**
 * @schema GatewayPodDisruptionBudget
 */
export interface GatewayPodDisruptionBudget {
  /**
   * @schema GatewayPodDisruptionBudget#minAvailable
   */
  readonly minAvailable?: any;

  /**
   * @schema GatewayPodDisruptionBudget#maxUnavailable
   */
  readonly maxUnavailable?: any;

  /**
   * @schema GatewayPodDisruptionBudget#unhealthyPodEvictionPolicy
   */
  readonly unhealthyPodEvictionPolicy?: GatewayPodDisruptionBudgetUnhealthyPodEvictionPolicy;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayPodDisruptionBudget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayResourcesLimits
 */
export interface GatewayResourcesLimits {
  /**
   * @schema GatewayResourcesLimits#cpu
   */
  readonly cpu?: string;

  /**
   * @schema GatewayResourcesLimits#memory
   */
  readonly memory?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayResourcesLimits#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayResourcesRequests
 */
export interface GatewayResourcesRequests {
  /**
   * @schema GatewayResourcesRequests#cpu
   */
  readonly cpu?: string;

  /**
   * @schema GatewayResourcesRequests#memory
   */
  readonly memory?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema GatewayResourcesRequests#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * @schema GatewayServiceIpFamilyPolicy
 */
export enum GatewayServiceIpFamilyPolicy {
  /** SingleStack */
  SINGLE_STACK = "SingleStack",
  /** PreferDualStack */
  PREFER_DUAL_STACK = "PreferDualStack",
  /** RequireDualStack */
  REQUIRE_DUAL_STACK = "RequireDualStack",
}

/**
 * @schema GatewayServicePorts
 */
export interface GatewayServicePorts {
  /**
   * @schema GatewayServicePorts#name
   */
  readonly name?: string;

  /**
   * @schema GatewayServicePorts#port
   */
  readonly port?: number;

  /**
   * @schema GatewayServicePorts#protocol
   */
  readonly protocol?: string;

  /**
   * @schema GatewayServicePorts#targetPort
   */
  readonly targetPort?: number;
}

/**
 * @schema GatewayPodDisruptionBudgetUnhealthyPodEvictionPolicy
 */
export enum GatewayPodDisruptionBudgetUnhealthyPodEvictionPolicy {
  /** IfHealthyBudget */
  IF_HEALTHY_BUDGET = "IfHealthyBudget",
  /** AlwaysAllow */
  ALWAYS_ALLOW = "AlwaysAllow",
}
