language: typescript
app: npx ts-node -r tsconfig-paths/register main.ts
imports:
  - k8s
  - helm:https://charts.jetstack.io/cert-manager@1.14.3
  - helm:https://bitnami-labs.github.io/sealed-secrets/sealed-secrets@2.15.0
  - helm:https://emberstack.github.io/helm-charts/reflector@7.1.256
  - helm:https://charts.jetstack.io/trust-manager@0.8.0
  - helm:https://istio-release.storage.googleapis.com/charts/istiod@1.21.0
  - helm:https://istio-release.storage.googleapis.com/charts/base@1.21.0
  - helm:https://istio-release.storage.googleapis.com/charts/gateway@1.20.3
  - helm:https://dl.gitea.com/charts/gitea@10.1.3
  - helm:https://woodpecker-ci.org/woodpecker@1.1.1
  - helm:https://charts.crossplane.io/stable/crossplane@1.15.0
  - helm:https://mysql.github.io/mysql-operator/mysql-operator@2.1.2
  - helm:https://mysql.github.io/mysql-operator/mysql-innodbcluster@2.1.2
  - cert-manager/challenges:=__crds/challenges.acme.cert-manager.io.yaml
  - cert-manager/certificaterequests:=__crds/certificaterequests.cert-manager.io.yaml
  - cert-manager/certificates:=__crds/certificates.cert-manager.io.yaml
  - cert-manager/clusterissuers:=__crds/clusterissuers.cert-manager.io.yaml
  - cert-manager/issuers:=__crds/issuers.cert-manager.io.yaml
  - cert-manager/orders:=__crds/orders.acme.cert-manager.io.yaml
  - trust-manager/bundles:=__crds/bundles.trust.cert-manager.io.yaml
  - istio/security-authorizationpolicies:=__crds/authorizationpolicies.security.istio.io.yaml
  - istio/networking-destinationrules:=__crds/destinationrules.networking.istio.io.yaml
  - istio/networking-envoyfilters:=__crds/envoyfilters.networking.istio.io.yaml
  - istio/networking-gateways:=__crds/gateways.networking.istio.io.yaml
  - istio/install-istiooperators:=__crds/istiooperators.install.istio.io.yaml
  - istio/security-peerauthentications:=__crds/peerauthentications.security.istio.io.yaml
  - istio/networking-proxyconfigs:=__crds/proxyconfigs.networking.istio.io.yaml
  - istio/security-requestauthentications:=__crds/requestauthentications.security.istio.io.yaml
  - istio/networking-serviceentries:=__crds/serviceentries.networking.istio.io.yaml
  - istio/networking-sidecars:=__crds/sidecars.networking.istio.io.yaml
  - istio/telemetry-telemetries:=__crds/telemetries.telemetry.istio.io.yaml
  - istio/networking-virtualservices:=__crds/virtualservices.networking.istio.io.yaml
  - istio/extensions-wasmplugins:=__crds/wasmplugins.extensions.istio.io.yaml
  - istio/networking-workloadentries:=__crds/workloadentries.networking.istio.io.yaml
  - istio/networking-workloadgroups:=__crds/workloadgroups.networking.istio.io.yaml
  - sealed-secrets/sealedsecrets:=__crds/sealedsecrets.bitnami.com.yaml
  - mysql/innodbclusters:=__crds/innodbclusters.mysql.oracle.com.yaml
  - mysql/mysqlbackups:=__crds/mysqlbackups.mysql.oracle.com.yaml
  - helm:https://kiali.org/helm-charts/kiali-server@1.81.0
  - helm:https://kubernetes.github.io/dashboard/kubernetes-dashboard@7.1.1
  - helm:https://kiali.org/helm-charts/kiali-operator@1.81.0
  - helm:https://falcosecurity.github.io/charts/falco@4.2.4
  - helm:https://falcosecurity.github.io/charts/falco-exporter@0.9.11
  - helm:https://helm.releases.hashicorp.com/vault@0.27.0
